<<<<<<< HEAD
# Generated by Django 4.2.7 on 2025-12-01 13:05

import django.contrib.auth.models
=======
# Generated by Django 4.2.7 on 2025-12-08 19:24

import clients.models
import django.contrib.auth.models
import django.core.validators
>>>>>>> e097b66e17a2ea974af903e357531f5ddcf8880b
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('produits', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
=======
>>>>>>> e097b66e17a2ea974af903e357531f5ddcf8880b
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(default='anonymes', max_length=30, unique=True)),
                ('prenom', models.CharField(blank=True, max_length=30, null=True)),
                ('nom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=128)),
                ('session_token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('token_expiration', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clients/')),
                ('groups', models.ManyToManyField(blank=True, related_name='clients_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='clients_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
=======
            name='AdresseFacturation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.TextField(help_text='Numéro et nom de rue', verbose_name='Adresse')),
                ('complement', models.CharField(blank=True, help_text='Appartement, bâtiment, etc.', max_length=255, verbose_name="Complément d'adresse")),
                ('code_postal', models.CharField(db_index=True, max_length=20, verbose_name='Code postal')),
                ('ville', models.CharField(db_index=True, max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('est_principale', models.BooleanField(default=False, help_text='Une seule adresse principale par client', verbose_name='Adresse principale')),
                ('date_ajoutee', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_modifiee', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Adresse de facturation',
                'verbose_name_plural': 'Adresses de facturation',
                'ordering': ['-est_principale', '-date_ajoutee'],
            },
        ),
        migrations.CreateModel(
            name='AdresseLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_destinataire', models.CharField(blank=True, help_text='Si différent du client', max_length=100, verbose_name='Nom du destinataire')),
                ('adresse', models.TextField(help_text='Numéro et nom de rue', verbose_name='Adresse')),
                ('complement', models.CharField(blank=True, help_text="Appartement, bâtiment, code d'accès, etc.", max_length=255, verbose_name="Complément d'adresse")),
                ('code_postal', models.CharField(db_index=True, max_length=20, verbose_name='Code postal')),
                ('ville', models.CharField(db_index=True, max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('telephone', models.CharField(blank=True, help_text='Pour le livreur', max_length=20, verbose_name='Téléphone de contact')),
                ('instructions', models.TextField(blank=True, help_text='Digicode, étage, sonnette, etc.', verbose_name='Instructions de livraison')),
                ('est_principale', models.BooleanField(default=False, help_text='Une seule adresse principale par client', verbose_name='Adresse principale')),
                ('date_ajoutee', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_modifiee', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Adresse de livraison',
                'verbose_name_plural': 'Adresses de livraison',
                'ordering': ['-est_principale', '-date_ajoutee'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(db_index=True, default='anonyme', help_text='Requis. 150 caractères max. Lettres, chiffres et @/./+/-/_ uniquement.', max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name="Nom d'utilisateur")),
                ('prenom', models.CharField(blank=True, max_length=50, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom de famille')),
                ('email', models.EmailField(db_index=True, error_messages={'unique': 'Un compte avec cet email existe déjà.'}, max_length=254, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, help_text='Format: +33 6 12 34 56 78', max_length=20, null=True, verbose_name='Téléphone')),
                ('image', models.ImageField(blank=True, help_text='Format recommandé: 300x300px, JPG/PNG', null=True, upload_to=clients.models.client_image_upload_path, verbose_name='Photo de profil')),
                ('session_token', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Token de session')),
                ('token_expiration', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Expiration du token')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('date_derniere_connexion', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Décocher pour désactiver le compte sans le supprimer', verbose_name='Compte actif')),
                ('is_verified', models.BooleanField(default=False, help_text="True si l'email a été vérifié", verbose_name='Email vérifié')),
                ('newsletter', models.BooleanField(default=False, help_text='Recevoir les actualités et promotions', verbose_name='Newsletter')),
                ('notifications_commande', models.BooleanField(default=True, help_text='Recevoir les notifications de suivi de commande', verbose_name='Notifications commandes')),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español')], default='fr', max_length=10, verbose_name='Langue préférée')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-date_inscription'],
>>>>>>> e097b66e17a2ea974af903e357531f5ddcf8880b
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='NavigationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('path', models.CharField(max_length=1024)),
                ('user_agent', models.CharField(max_length=1024)),
                ('referrer', models.CharField(blank=True, max_length=1024, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('os_info', models.CharField(blank=True, max_length=255, null=True)),
                ('device_type', models.CharField(default='desktop', max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_duration', models.PositiveIntegerField(default=0)),
                ('fingerprint', models.CharField(blank=True, max_length=1024, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.produit')),
            ],
        ),
        migrations.CreateModel(
            name='AdresseLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.TextField(blank=True, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('pays', models.CharField(blank=True, max_length=100, null=True)),
                ('date_ajoutee', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresse_livraison', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='AdresseFacturation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.TextField(blank=True, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('pays', models.CharField(blank=True, max_length=100, null=True)),
                ('date_ajoutee', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresse_facturation', to='clients.client')),
            ],
=======
                ('path', models.CharField(db_index=True, max_length=1024, verbose_name='Chemin URL')),
                ('user_agent', models.CharField(max_length=1024, verbose_name='User Agent')),
                ('referrer', models.CharField(blank=True, db_index=True, max_length=1024, null=True, verbose_name='Référent')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='Adresse IP')),
                ('os_info', models.CharField(blank=True, max_length=255, null=True, verbose_name="Système d'exploitation")),
                ('device_type', models.CharField(choices=[('desktop', '🖥️ Desktop'), ('tablet', '📱 Tablette'), ('mobile', '📱 Mobile'), ('bot', '🤖 Bot')], db_index=True, default='desktop', max_length=50, verbose_name="Type d'appareil")),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date et heure')),
                ('session_duration', models.PositiveIntegerField(default=0, verbose_name='Durée de session (secondes)')),
                ('fingerprint', models.CharField(blank=True, db_index=True, max_length=1024, null=True, verbose_name='Empreinte navigateur')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_logs', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Log de navigation',
                'verbose_name_plural': 'Logs de navigation',
                'ordering': ['-timestamp'],
            },
>>>>>>> e097b66e17a2ea974af903e357531f5ddcf8880b
        ),
    ]
