# Generated by Django 4.2.7 on 2025-12-08 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('produits', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationlog',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_logs', to='produits.produit', verbose_name='Produit consulté'),
        ),
        migrations.AddField(
            model_name='client',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Les groupes auxquels appartient cet utilisateur.', related_name='clients_set', to='auth.group', verbose_name='Groupes'),
        ),
        migrations.AddField(
            model_name='client',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions spécifiques pour cet utilisateur.', related_name='clients_set', to='auth.permission', verbose_name='Permissions'),
        ),
        migrations.AddField(
            model_name='adresselivraison',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresse_livraison', to='clients.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='adressefacturation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresse_facturation', to='clients.client', verbose_name='Client'),
        ),
        migrations.AddIndex(
            model_name='navigationlog',
            index=models.Index(fields=['-timestamp', 'client'], name='clients_nav_timesta_f0c80d_idx'),
        ),
        migrations.AddIndex(
            model_name='navigationlog',
            index=models.Index(fields=['produit', '-timestamp'], name='clients_nav_produit_1ef98e_idx'),
        ),
        migrations.AddIndex(
            model_name='navigationlog',
            index=models.Index(fields=['device_type', '-timestamp'], name='clients_nav_device__eedfbb_idx'),
        ),
        migrations.AddIndex(
            model_name='navigationlog',
            index=models.Index(fields=['ip_address', '-timestamp'], name='clients_nav_ip_addr_6fee73_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='clients_cli_email_56b9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['username'], name='clients_cli_usernam_c6e1dc_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['session_token'], name='clients_cli_session_276df2_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_active', '-date_inscription'], name='clients_cli_is_acti_8afa6c_idx'),
        ),
        migrations.AddIndex(
            model_name='adresselivraison',
            index=models.Index(fields=['client', '-date_ajoutee'], name='clients_adr_client__8df6d9_idx'),
        ),
        migrations.AddIndex(
            model_name='adresselivraison',
            index=models.Index(fields=['code_postal', 'ville'], name='clients_adr_code_po_aeb08b_idx'),
        ),
        migrations.AddIndex(
            model_name='adressefacturation',
            index=models.Index(fields=['client', '-date_ajoutee'], name='clients_adr_client__496ddb_idx'),
        ),
        migrations.AddIndex(
            model_name='adressefacturation',
            index=models.Index(fields=['code_postal', 'ville'], name='clients_adr_code_po_4400ed_idx'),
        ),
    ]
