# Generated by Django 4.2.7 on 2025-12-09 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nom de famille'),
        ),
        migrations.CreateModel(
            name='ClientToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Clé')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Token Client',
                'verbose_name_plural': 'Tokens Clients',
            },
        ),
    ]
