# Generated by Django 4.2.7 on 2025-12-08 19:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du livreur')),
                ('telephone', models.CharField(max_length=15, verbose_name='Téléphone')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse complète')),
                ('cle_api', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Clé API')),
                ('date_ajoutee', models.DateTimeField(auto_now_add=True)),
                ('date_modifiee', models.DateTimeField(auto_now=True)),
                ('type_service', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express')], db_index=True, default='standard', max_length=20)),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Livreur',
                'verbose_name_plural': 'Livreurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids_min', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Poids minimum (kg)')),
                ('poids_max', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Poids maximum (kg)')),
                ('prix_ht', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix HT')),
                ('prix_ttc', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix TTC')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Taux TVA (%)')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='livraisons.livreur', verbose_name='Livreur')),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tarifs',
                'ordering': ['livreur', 'poids_min'],
            },
        ),
        migrations.CreateModel(
            name='PointRelais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du point relais')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('code_postal', models.CharField(db_index=True, max_length=10, verbose_name='Code postal')),
                ('ville', models.CharField(db_index=True, max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90.0')), django.core.validators.MaxValueValidator(Decimal('90.0'))], verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180.0')), django.core.validators.MaxValueValidator(Decimal('180.0'))], verbose_name='Longitude')),
                ('horaires_ouverture', models.TextField(blank=True, help_text='Exemple: Lun-Ven: 9h-18h, Sam: 9h-12h', verbose_name="Horaires d'ouverture")),
                ('telephone', models.CharField(blank=True, max_length=15, verbose_name='Téléphone')),
                ('capacite_max', models.PositiveIntegerField(default=50, help_text='Nombre de colis maximum stockables', verbose_name='Capacité maximale')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Point relais',
                'verbose_name_plural': 'Points relais',
                'ordering': ['ville', 'nom'],
                'indexes': [models.Index(fields=['code_postal', 'ville', 'est_actif'], name='livraisons__code_po_eb055e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='livreur',
            index=models.Index(fields=['email', 'est_actif'], name='livraisons__email_8c8ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='livreur',
            index=models.Index(fields=['type_service', 'est_actif'], name='livraisons__type_se_38538a_idx'),
        ),
        migrations.AddIndex(
            model_name='tarif',
            index=models.Index(fields=['livreur', 'poids_min', 'poids_max'], name='livraisons__livreur_3f934f_idx'),
        ),
        migrations.AddConstraint(
            model_name='tarif',
            constraint=models.CheckConstraint(check=models.Q(('poids_max__gt', models.F('poids_min'))), name='poids_max_superieur_poids_min'),
        ),
    ]
