<<<<<<< HEAD
# Generated by Django 4.2.7 on 2025-12-01 13:05

from django.conf import settings
=======
# Generated by Django 4.2.7 on 2025-12-08 19:24

from decimal import Decimal
import django.core.validators
>>>>>>> e097b66e17a2ea974af903e357531f5ddcf8880b
from django.db import migrations, models
import django.db.models.deletion
import produits.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        ('fournisseur', '0001_initial'),
>>>>>>> e097b66e17a2ea974af903e357531f5ddcf8880b
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('metier', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=15)),
                ('adresse', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('date_ajoutee', models.DateTimeField(auto_now_add=True)),
                ('date_modifiee', models.DateTimeField(auto_now=True)),
                ('type_production', models.CharField(choices=[('permaculture', 'Permaculture'), ('biologique', 'Biologique'), ('raisonnee', 'Agriculture Raisonnée'), ('autre', 'Autre')], default='autre', max_length=100)),
                ('experience_annees', models.PositiveIntegerField(blank=True, null=True)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('engagement_ecologique', models.TextField(blank=True, null=True)),
                ('conditions_travail', models.TextField(blank=True, null=True)),
                ('objectifs_durables', models.TextField(blank=True, null=True)),
                ('produits_principaux', models.TextField(blank=True, null=True)),
                ('calendrier_production', models.TextField(blank=True, null=True)),
                ('saisonnalite_respectee', models.BooleanField(default=True)),
                ('temoignages_clients', models.TextField(blank=True, null=True)),
                ('impact_local', models.TextField(blank=True, null=True)),
                ('pays', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=produits.models.fournisseur_photo_upload_path)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='logos/')),
            ],
=======
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, help_text="Emoji ou classe d'icône (ex: 🍷 ou fa-wine)", max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('ordre', models.IntegerField(default=0)),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'nom'],
            },
>>>>>>> e097b66e17a2ea974af903e357531f5ddcf8880b
        ),
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('nom', models.CharField(max_length=255)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='produits.categorie')),
            ],
=======
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='souscategories/')),
                ('ordre', models.IntegerField(default=0)),
                ('est_active', models.BooleanField(default=True)),
                ('descripteurs_specifiques', models.JSONField(blank=True, default=dict, help_text='Descripteurs additionnels propres à cette sous-catégorie')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souscategories', to='produits.categorie', verbose_name='Catégorie parente')),
            ],
            options={
                'verbose_name': 'Sous-catégorie',
                'verbose_name_plural': 'Sous-catégories',
                'ordering': ['categorie__ordre', 'ordre', 'nom'],
                'unique_together': {('categorie', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='SousSousCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='soussouscategories/')),
                ('ordre', models.IntegerField(default=0)),
                ('est_active', models.BooleanField(default=True)),
                ('descripteurs_specifiques', models.JSONField(blank=True, default=dict, help_text='Descripteurs additionnels propres à cette sous-sous-catégorie')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('souscategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soussouscategories', to='produits.souscategorie', verbose_name='Sous-catégorie parente')),
            ],
            options={
                'verbose_name': 'Sous-sous-catégorie',
                'verbose_name_plural': 'Sous-sous-catégories',
                'ordering': ['souscategorie__categorie__ordre', 'souscategorie__ordre', 'ordre', 'nom'],
                'unique_together': {('souscategorie', 'slug')},
            },
>>>>>>> e097b66e17a2ea974af903e357531f5ddcf8880b
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_longue', models.TextField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=produits.models.produit_image_upload_path)),
                ('grande_image', models.ImageField(blank=True, null=True, upload_to=produits.models.produit_image_upload_path)),
                ('date_ajoute', models.DateTimeField(auto_now_add=True)),
                ('date_modifie', models.DateTimeField(auto_now=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to=produits.models.qr_code_upload_path)),
                ('numero_unique', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('adresse_produit', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cycle_fabrication', models.TextField(blank=True, help_text='Décrire le cycle de fabrication (ex : plantation, récolte, pressage, etc.)', null=True)),
                ('preparation', models.TextField(blank=True, help_text='Détails sur les méthodes de préparation ou de transformation (ex : extraction à froid).', null=True)),
                ('date_recolte', models.DateField(blank=True, help_text="Date de récolte (utile pour des produits comme l'huile d'olive ou les fruits).", null=True)),
                ('origine', models.CharField(blank=True, help_text='Origine géographique du produit (ex : Provence, France).', max_length=255, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_preparation', 'En préparation'), ('en_livraison', 'En livraison'), ('termine', 'Terminé'), ('en_stock', 'En stock')], default='en_attente', max_length=20)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=20.0, help_text='Taux de TVA en pourcentage (ex : 20 pour 20%)', max_digits=4)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='produits.categorie')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='produits.fournisseur')),
                ('logos', models.ManyToManyField(blank=True, to='produits.logo')),
                ('souscategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='produits.souscategorie')),
            ],
=======
                ('numero_unique', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Numéro unique')),
                ('code_barre', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Code-barres (EAN/UPC)')),
                ('reference_interne', models.CharField(blank=True, max_length=100, verbose_name='Référence interne')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description_courte', models.TextField(blank=True, help_text='Description courte pour les listes (max 300 caractères)', max_length=300, verbose_name='Description courte')),
                ('description_longue', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to=produits.models.image_upload_path, verbose_name='Image principale')),
                ('prix_ht', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix HT (€)')),
                ('tva', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Taux de TVA applicable', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='TVA (%)')),
                ('stock_actuel', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock actuel')),
                ('stock_minimum', models.IntegerField(default=0, help_text="Seuil d'alerte pour le réapprovisionnement", validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock minimum')),
                ('en_promotion', models.BooleanField(default=False, verbose_name='En promotion')),
                ('pourcentage_promotion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pourcentage de réduction', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Réduction (%)')),
                ('statut', models.CharField(choices=[('en_attente', '⏳ En attente'), ('en_preparation', '🔄 En préparation'), ('en_livraison', '🚚 En livraison'), ('en_stock', '✅ En stock'), ('arrivee', '📥 Arrivé'), ('rupture', '❌ Rupture de stock'), ('archive', '📦 Archivé')], default='en_stock', max_length=20, verbose_name='Statut')),
                ('est_actif', models.BooleanField(default=True, help_text='Décocher pour désactiver le produit sans le supprimer', verbose_name='Actif')),
                ('est_nouveaute', models.BooleanField(default=False, verbose_name='Nouveauté')),
                ('est_bio', models.BooleanField(default=False, verbose_name='Bio')),
                ('est_local', models.BooleanField(default=False, verbose_name='Produit local')),
                ('poids', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Poids (kg)')),
                ('unite_mesure', models.CharField(default='unité', help_text='Ex: kg, L, unité, boîte', max_length=20, verbose_name='Unité de mesure')),
                ('origine', models.CharField(blank=True, help_text="Pays ou région d'origine", max_length=100, verbose_name='Origine/Provenance')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to=produits.models.qr_code_upload_path, verbose_name='QR Code')),
                ('meta_title', models.CharField(blank=True, help_text='Titre pour le SEO (max 70 caractères)', max_length=70, verbose_name='Meta titre')),
                ('meta_description', models.TextField(blank=True, help_text='Description pour le SEO (max 160 caractères)', max_length=160, verbose_name='Meta description')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_ajout_stock', models.DateTimeField(blank=True, null=True, verbose_name="Date d'ajout au stock")),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='produits.categorie', verbose_name='Catégorie principale')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='fournisseur.fournisseur', verbose_name='Fournisseur')),
                ('souscategorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='produits.souscategorie', verbose_name='Sous-catégorie')),
                ('soussouscategorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='produits.soussouscategorie', verbose_name='Sous-sous-catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LogoLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Bio, AOP, IGP, Label Rouge', max_length=100, verbose_name='Nom du label')),
                ('image', models.ImageField(upload_to='labels/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='produits.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Logo/Label',
                'verbose_name_plural': 'Logos/Labels',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=produits.models.image_upload_path, verbose_name='Image')),
                ('legende', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('est_principale', models.BooleanField(default=False, verbose_name='Image principale')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='produits.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Image produit',
                'verbose_name_plural': 'Images produits',
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='DescripteurProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(help_text='Ex: millesime, cepage, region', max_length=100, verbose_name='Clé du descripteur')),
                ('valeur', models.TextField(help_text='La valeur du descripteur', verbose_name='Valeur')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descripteurs', to='produits.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Descripteur produit',
                'verbose_name_plural': 'Descripteurs produits',
                'ordering': ['ordre', 'cle'],
            },
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['numero_unique'], name='produits_pr_numero__aee393_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['slug'], name='produits_pr_slug_e18bf1_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['code_barre'], name='produits_pr_code_ba_6aba8a_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['statut'], name='produits_pr_statut_4f7089_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['est_actif'], name='produits_pr_est_act_724b33_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['categorie', 'souscategorie', 'soussouscategorie'], name='produits_pr_categor_bd157c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='descripteurproduit',
            unique_together={('produit', 'cle')},
>>>>>>> e097b66e17a2ea974af903e357531f5ddcf8880b
        ),
    ]
