# Generated by Django 4.2.7 on 2025-12-01 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import produits.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('metier', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=15)),
                ('adresse', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('date_ajoutee', models.DateTimeField(auto_now_add=True)),
                ('date_modifiee', models.DateTimeField(auto_now=True)),
                ('type_production', models.CharField(choices=[('permaculture', 'Permaculture'), ('biologique', 'Biologique'), ('raisonnee', 'Agriculture Raisonnée'), ('autre', 'Autre')], default='autre', max_length=100)),
                ('experience_annees', models.PositiveIntegerField(blank=True, null=True)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('engagement_ecologique', models.TextField(blank=True, null=True)),
                ('conditions_travail', models.TextField(blank=True, null=True)),
                ('objectifs_durables', models.TextField(blank=True, null=True)),
                ('produits_principaux', models.TextField(blank=True, null=True)),
                ('calendrier_production', models.TextField(blank=True, null=True)),
                ('saisonnalite_respectee', models.BooleanField(default=True)),
                ('temoignages_clients', models.TextField(blank=True, null=True)),
                ('impact_local', models.TextField(blank=True, null=True)),
                ('pays', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=produits.models.fournisseur_photo_upload_path)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='produits.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_longue', models.TextField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=produits.models.produit_image_upload_path)),
                ('grande_image', models.ImageField(blank=True, null=True, upload_to=produits.models.produit_image_upload_path)),
                ('date_ajoute', models.DateTimeField(auto_now_add=True)),
                ('date_modifie', models.DateTimeField(auto_now=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to=produits.models.qr_code_upload_path)),
                ('numero_unique', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('adresse_produit', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cycle_fabrication', models.TextField(blank=True, help_text='Décrire le cycle de fabrication (ex : plantation, récolte, pressage, etc.)', null=True)),
                ('preparation', models.TextField(blank=True, help_text='Détails sur les méthodes de préparation ou de transformation (ex : extraction à froid).', null=True)),
                ('date_recolte', models.DateField(blank=True, help_text="Date de récolte (utile pour des produits comme l'huile d'olive ou les fruits).", null=True)),
                ('origine', models.CharField(blank=True, help_text='Origine géographique du produit (ex : Provence, France).', max_length=255, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_preparation', 'En préparation'), ('en_livraison', 'En livraison'), ('termine', 'Terminé'), ('en_stock', 'En stock')], default='en_attente', max_length=20)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=20.0, help_text='Taux de TVA en pourcentage (ex : 20 pour 20%)', max_digits=4)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='produits.categorie')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='produits.fournisseur')),
                ('logos', models.ManyToManyField(blank=True, to='produits.logo')),
                ('souscategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='produits.souscategorie')),
            ],
        ),
    ]
