# Generated by Django 4.2.7 on 2025-12-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='descripteurs',
            field=models.JSONField(blank=True, default=dict, help_text='Descripteurs communs à tous les produits de cette catégorie', verbose_name='Descripteurs'),
        ),
    ]
