# Generated by Django 4.2.7 on 2025-12-08 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_categorie_descripteurs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='souscategorie',
            old_name='descripteurs_specifiques',
            new_name='descripteurs',
        ),
        migrations.RenameField(
            model_name='soussouscategorie',
            old_name='descripteurs_specifiques',
            new_name='descripteurs',
        ),
    ]
