<<<<<<< HEAD
# Generated by Django 4.2.7 on 2025-12-01 13:05
=======
# Generated by Django 4.2.7 on 2025-12-08 19:24
>>>>>>> e097b66e17a2ea974af903e357531f5ddcf8880b

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('termine', 'Terminé')], default='actif', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panier', to='clients.client')),
            ],
=======
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('termine', 'Terminé'), ('archive', 'Archivé')], default='actif', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paniers', to='clients.client')),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
                'ordering': ['-date_creation'],
            },
>>>>>>> e097b66e17a2ea974af903e357531f5ddcf8880b
        ),
        migrations.CreateModel(
            name='LignePanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('date_ajoutee', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_preparation', 'En préparation'), ('en_livraison', 'En livraison'), ('termine', 'Terminé'), ('en_stock', 'En stock')], default='en_attente', max_length=20)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='paniers.panier')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
            ],
=======
                ('statut', models.CharField(choices=[('en_attente', '⏳ En attente'), ('en_preparation', '🔄 En préparation'), ('en_livraison', '🚚 En livraison'), ('en_stock', '✅ En stock'), ('arrivee', '📥 Arrivé'), ('rupture', '❌ Rupture de stock'), ('archive', '📦 Archivé')], default='en_attente', max_length=20, verbose_name='Statut de préparation')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='paniers.panier')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
            ],
            options={
                'verbose_name': 'Ligne de panier',
                'verbose_name_plural': 'Lignes de panier',
                'ordering': ['date_ajoutee'],
                'unique_together': {('panier', 'produit')},
            },
>>>>>>> e097b66e17a2ea974af903e357531f5ddcf8880b
        ),
    ]
