# Generated by Django 4.2.7 on 2025-12-08 19:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import fournisseur.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Entrez une adresse email valide.')], verbose_name='Email')),
                ('metier', models.CharField(max_length=100, verbose_name='Métier')),
                ('contact', models.CharField(max_length=100, verbose_name='Contact')),
                ('tel', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone')),
                ('adresse', models.TextField(verbose_name='Adresse complète')),
                ('code_postal', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('zone_livraison_type', models.CharField(choices=[('rayon', 'Rayon kilométrique'), ('departements', 'Départements'), ('villes', 'Villes spécifiques'), ('national', 'National')], default='rayon', max_length=50, verbose_name='Type de zone de livraison')),
                ('rayon_livraison_km', models.PositiveIntegerField(blank=True, help_text="Distance maximale de livraison depuis l'adresse principale", null=True, verbose_name='Rayon de livraison (km)')),
                ('departements_livraison', models.TextField(blank=True, help_text='Ex: 75, 77, 78, 91, 92, 93, 94, 95 (séparés par des virgules)', verbose_name='Départements de livraison')),
                ('villes_livraison', models.TextField(blank=True, help_text='Ex: Paris, Lyon, Marseille (séparées par des virgules)', verbose_name='Villes de livraison')),
                ('frais_livraison_base', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Frais de livraison de base (€)')),
                ('frais_livraison_par_km', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, verbose_name='Frais par km supplémentaire (€)')),
                ('livraison_gratuite_montant', models.DecimalField(blank=True, decimal_places=2, help_text='Montant minimum de commande pour livraison gratuite', max_digits=6, null=True, verbose_name='Montant pour livraison gratuite (€)')),
                ('jours_livraison', models.CharField(blank=True, help_text='Ex: Lundi, Mercredi, Vendredi', max_length=200, verbose_name='Jours de livraison')),
                ('delai_livraison_jours', models.PositiveIntegerField(default=2, help_text='Nombre de jours entre la commande et la livraison', verbose_name='Délai de livraison (jours)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type_production', models.CharField(choices=[('permaculture', 'Permaculture'), ('biologique', 'Biologique'), ('raisonnee', 'Agriculture Raisonnée'), ('autre', 'Autre')], default='autre', max_length=100, verbose_name='Type de production')),
                ('experience_annees', models.PositiveIntegerField(blank=True, null=True, verbose_name="Années d'expérience")),
                ('certifications', models.TextField(blank=True, help_text='Ex: AB, Ecocert, Fairtrade', null=True, verbose_name='Certifications')),
                ('engagement_ecologique', models.TextField(blank=True, null=True, verbose_name='Engagement écologique')),
                ('conditions_travail', models.TextField(blank=True, null=True, verbose_name='Conditions de travail')),
                ('objectifs_durables', models.TextField(blank=True, null=True, verbose_name='Objectifs durables')),
                ('produits_principaux', models.TextField(blank=True, help_text='Ex: Tomates, Courges, Laitue', null=True, verbose_name='Produits principaux')),
                ('calendrier_production', models.TextField(blank=True, help_text='Ex: Mars à Novembre', null=True, verbose_name='Calendrier de production')),
                ('saisonnalite_respectee', models.BooleanField(default=True, verbose_name='Saisonnalité respectée')),
                ('temoignages_clients', models.TextField(blank=True, null=True, verbose_name='Témoignages clients')),
                ('impact_local', models.TextField(blank=True, null=True, verbose_name='Impact local')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=fournisseur.models.fournisseur_photo_upload_path, verbose_name='Photo')),
                ('date_ajoutee', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_modifiee', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Client associé')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='ZoneLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la zone')),
                ('departements', models.TextField(blank=True, help_text='Codes départements séparés par des virgules', verbose_name='Départements')),
                ('villes', models.TextField(blank=True, help_text='Noms de villes séparés par des virgules', verbose_name='Villes')),
                ('frais_livraison', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Frais de livraison (€)')),
                ('delai_livraison_jours', models.PositiveIntegerField(verbose_name='Délai de livraison (jours)')),
                ('montant_minimum', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Montant minimum de commande (€)')),
                ('actif', models.BooleanField(default=True, verbose_name='Zone active')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones_livraison', to='fournisseur.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Zone de livraison',
                'verbose_name_plural': 'Zones de livraison',
                'ordering': ['fournisseur', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='PointLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du point')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('code_postal', models.CharField(max_length=10, verbose_name='Code postal')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('type_point', models.CharField(choices=[('marche', 'Marché'), ('depot', 'Dépôt'), ('magasin', 'Magasin'), ('autre', 'Autre')], default='depot', max_length=50, verbose_name='Type de point')),
                ('horaires', models.TextField(blank=True, help_text='Ex: Lundi-Vendredi: 9h-18h', verbose_name="Horaires d'ouverture")),
                ('jours_disponibles', models.CharField(blank=True, help_text='Ex: Lundi, Mercredi, Vendredi', max_length=200, verbose_name='Jours disponibles')),
                ('instructions', models.TextField(blank=True, help_text='Informations pour récupérer la commande', verbose_name='Instructions de retrait')),
                ('actif', models.BooleanField(default=True, verbose_name='Point actif')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Point de livraison',
                'verbose_name_plural': 'Points de livraison',
                'ordering': ['ville', 'nom'],
                'indexes': [models.Index(fields=['ville', 'code_postal'], name='fournisseur_ville_e82e75_idx'), models.Index(fields=['actif'], name='fournisseur_actif_590921_idx')],
            },
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='points_livraison',
            field=models.ManyToManyField(blank=True, related_name='fournisseurs', to='fournisseur.pointlivraison', verbose_name='Points de livraison'),
        ),
        migrations.AddIndex(
            model_name='fournisseur',
            index=models.Index(fields=['ville', 'code_postal'], name='fournisseur_ville_f9fbde_idx'),
        ),
        migrations.AddIndex(
            model_name='fournisseur',
            index=models.Index(fields=['zone_livraison_type'], name='fournisseur_zone_li_0d7db2_idx'),
        ),
    ]
