"""
Django settings for back project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from pathlib import Path
import pymysql
import os
from dotenv import load_dotenv
from corsheaders.defaults import default_headers
from datetime import timedelta
<<<<<<< HEAD

=======
load_dotenv()
>>>>>>> e097b66e17a2ea974af903e357531f5ddcf8880b

# ============================================================================
# PYMYSQL CONFIGURATION
# ============================================================================
pymysql.install_as_MySQLdb()

# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# Les variables d'environnement sont déjà chargées par Docker via docker-compose.yml
# Pas besoin de load_dotenv() en production
ENVIRONMENT = os.getenv('ENVIRONMENT', 'local')
print(f"📋 Environment: {ENVIRONMENT}")

# Debug mode
DEBUG_STR = os.getenv('DEBUG', 'True')
DEBUG = DEBUG_STR.lower() not in ['false', '0', 'no', 'off', 'n', 'f']
# Détection environnement
IS_LOCAL = os.getenv('IS_LOCAL', 'False').lower() in ('true', '1', 't')
IS_DOCKER = os.getenv('DOCKER', 'True').lower() in ('true', '1', 't')
USE_DOCKER = os.getenv('USE_DOCKER', 'False').lower() in ('true', '1', 't')



# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i%xj*prc&(=!w_y*xzlv^p8y4#$^jze18l^nr3i$r#4335%+l0'

# SECURITY WARNING: don't run with debug turned on in production!
print(f"🔧 DEBUG mode: {DEBUG}")
ALLOWED_HOSTS = ["*"]


# Application definition
# ===========================
# REST FRAMEWORK
# ===========================
# back/settings.py

REST_FRAMEWORK = {
<<<<<<< HEAD
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'patients.authentication.PatientJWTAuthentication',  # ✅ Ta classe custom EN PREMIER
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',  # Par défaut ouvert
    ),
    'DEFAULT_RENDERER_CLASSES': (
        
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
=======
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.authentication.ClientTokenAuthentication',  # ← Token personnalisé basé sur Client.session_token
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
>>>>>>> e097b66e17a2ea974af903e357531f5ddcf8880b
}

# Configuration JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,  # ❌ Pas de blacklist
    'BLACKLIST_AFTER_ROTATION': False,  # ❌ Pas de blacklist
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# Logging pour debug
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
<<<<<<< HEAD
        'patients.authentication': {
=======
        'clients.authentication': {
>>>>>>> e097b66e17a2ea974af903e357531f5ddcf8880b
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}

# ===========================
# SIMPLE JWT
# ===========================
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    
    # ✅ DÉSACTIVER la blacklist car elle ne fonctionne qu'avec AUTH_USER_MODEL
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
<<<<<<< HEAD
    'rest_framework_simplejwt',
    'django_browser_reload',
    'authentification',
    'Home',
    'produits',
    'clients',
=======
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'django_browser_reload',
    'api',
    'Home',
    'clients',      # ⚠️ DOIT ÊTRE AVANT 'fournisseurs'
    'fournisseur',
    'produits',
>>>>>>> e097b66e17a2ea974af903e357531f5ddcf8880b
    'paniers',
    'commandes',
    'livraisons',
    'utils',


<<<<<<< HEAD



=======
>>>>>>> e097b66e17a2ea974af903e357531f5ddcf8880b
    'corsheaders',# CORS et configuration pour permettre les appels depuis React
    'drf_yasg',


]
# settings.py

# ============================================================================
# CORS 
# ============================================================================

# Détection environnement
IS_LOCAL = os.getenv('IS_LOCAL', 'False').lower() in ('true', '1', 't')
IS_DOCKER = os.getenv('DOCKER', 'True').lower() in ('true', '1', 't')

# URLs selon l'environnement
if IS_LOCAL:
    FRONTEND_URL = 'http://localhost:3007'
    BACKEND_URL = 'http://localhost:8007'
else:  # DOCKER
    FRONTEND_URL =  'laprovidence.data-worlds.com',
    BACKEND_URL =   'api-laprovidence.data-worlds.com'


# ✅ Override avec variables d'environnement
FRONTEND_URL = os.getenv('FRONTEND_URL', FRONTEND_URL)
BACKEND_URL = os.getenv('BACKEND_URL', BACKEND_URL)

print(f"🌐 URLs Configuration:")
print(f"   Frontend: {FRONTEND_URL}")
print(f"   Backend: {BACKEND_URL}\n")


CORS_ALLOWED_ORIGINS = [
      'http://localhost:3007',  # Pour dev local
      'http://localhost:8007',  # Pour dev local
     'https://api-laprovidence.data-worlds.com',
     'https://laprovidence.data-worlds.com'
    ]

# settings.py


CORS_ALLOW_HEADERS = list(default_headers) + [
    'Authorization',
    'Content-Type',  # Ajouter 'Content-Type' si nécessaire
]
CORS_ALLOW_CREDENTIALS = True

# Si tu travailles en développement local
CSRF_COOKIE_SECURE = False  # Ne pas utiliser HTTPS en local
CSRF_USE_SESSIONS = False

CSRF_TRUSTED_ORIGINS = [
      'http://localhost:3007',  # Pour dev local
        'https://api-laprovidence.data-worlds.com',
     'https://laprovidence.data-worlds.com'

]

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS'
]






<<<<<<< HEAD
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {'max_similarity': 0.7}
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10}  # Exemple : augmenter à 10
    },
    # ... autres validateurs
=======
# ===========================
# AUTHENTICATION BACKENDS
# ===========================
# Permet aux fournisseurs de se connecter avec leur email/password
AUTHENTICATION_BACKENDS = [
    'fournisseur.backends.FournisseurAuthBackend',  # Backend pour les fournisseurs
    'django.contrib.auth.backends.ModelBackend',     # Backend par défaut (admins)
]

# Validation minimale pour améliorer les performances
# Vous pouvez activer plus de validateurs en production
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8}  # Minimum 8 caractères
    },
>>>>>>> e097b66e17a2ea974af903e357531f5ddcf8880b
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django_browser_reload.middleware.BrowserReloadMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
<<<<<<< HEAD
=======

>>>>>>> e097b66e17a2ea974af903e357531f5ddcf8880b
]




ROOT_URLCONF = 'back.urls'
<<<<<<< HEAD
TEMPLATE_DIRS = [os.path.join(BASE_DIR, 'web', 'Base')]
TEMPLATE_DIRS += [os.path.join(BASE_DIR, 'web', 'authentification')]

TEMPLATE_DIRS += [os.path.join(BASE_DIR, 'web', 'Home')]
TEMPLATE_DIRS += [os.path.join(BASE_DIR, 'web', 'Base','Error')]
TEMPLATE_DIRS += [os.path.join(BASE_DIR, 'web', 'produits')]
TEMPLATE_DIRS += [os.path.join(BASE_DIR, 'web', 'commandes')]
=======
TEMPLATE_DIRS = [os.path.join(BASE_DIR, 'web', 'templates')]
TEMPLATE_DIRS += [os.path.join(BASE_DIR, 'web', 'templates','Error')]
TEMPLATE_DIRS += [os.path.join(BASE_DIR, 'fournisseur', 'templates')]

>>>>>>> e097b66e17a2ea974af903e357531f5ddcf8880b

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': TEMPLATE_DIRS,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
<<<<<<< HEAD
=======
                'web.context_processors.media_url' # ✅ Ajouter
>>>>>>> e097b66e17a2ea974af903e357531f5ddcf8880b

            ],

        },
    },
]

WSGI_APPLICATION = 'back.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


DATABASES = {
    'default': {
<<<<<<< HEAD
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DATABASE_NAME', 'LaProvidenceDev'),
        'USER': os.getenv('DATABASE_USER', 'DataWorlds'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD', ' '),
        'HOST': os.getenv('DATABASE_HOST', 'dataworlds.direct.quickconnect.to'),
        'PORT': os.getenv('DATABASE_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'use_unicode': True,
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'connect_timeout': 10,
        },

    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
=======
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DATABASE_NAME', 'DevLaProvidence'),
        'USER': os.getenv('DATABASE_USER', 'DataWorlds'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD', ' '),
        'HOST': os.getenv('DATABASE_HOST', 'dataworlds.direct.quickconnect.to'),
        'PORT': os.getenv('DATABASE_PORT', '5433'),
        'CONN_MAX_AGE': 600,  # Réutiliser les connexions pendant 10 minutes
        'CONN_HEALTH_CHECKS': True,  # Vérifier la santé de la connexion
        'OPTIONS': {
            'connect_timeout': 10,
            'options': '-c statement_timeout=30000',  # Timeout des requêtes à 30 secondes
            'keepalives': 1,
            'keepalives_idle': 30,
            'keepalives_interval': 10,
            'keepalives_count': 5,
        }
    }
}

# Password validation (déjà défini plus haut, suppression du doublon)
>>>>>>> e097b66e17a2ea974af903e357531f5ddcf8880b
 
# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'FR-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# ==========================================
# STATIC FILES
# ==========================================

STATIC_URL = '/static/'

# Répertoires contenant les fichiers statiques sources (développement)
STATICFILES_DIRS = [BASE_DIR / 'web' / 'static']

# ✅ CORRECTION : Chemin absolu pour collectstatic (production)
STATIC_ROOT = BASE_DIR / 'static'

# ==========================================
# MEDIA FILES
# ==========================================

MEDIA_URL = '/media/'

# ✅ CORRECTION : Chemin selon l'environnement
<<<<<<< HEAD
if USE_DOCKER:
   MEDIA_ROOT = Path('/app/media')

else:
    MEDIA_ROOT = BASE_DIR / 'media'
=======
# TOUJOURS sauvegarder sur le NAS Synology pour accessibilité client
if USE_DOCKER:
    # Production : Chemin du NAS dans le conteneur Docker
    MEDIA_ROOT = Path('/volume1/public/LaProvidence/media')
else:
    # Local : NAS monté sur Mac
    MEDIA_ROOT = Path('/Volumes/public/LaProvidence/media')

# ✅ URL de base pour les médias - TOUJOURS pointer vers le NAS pour que les clients puissent y accéder
# Cette URL sera utilisée pour construire les URLs complètes des images
MEDIA_BASE_URL = os.getenv(
        'MEDIA_BASE_URL','https://dataworlds.direct.quickconnect.to/public/LaProvidence/media/'
)
>>>>>>> e097b66e17a2ea974af903e357531f5ddcf8880b

# ==========================================
# WHITENOISE STORAGE
# ==========================================

<<<<<<< HEAD
# Configuration Whitenoise pour les MIME types
WHITENOISE_MIMETYPES = {
    '.css': 'text/css',
    '.js': 'application/javascript',
    '.json': 'application/json',
    '.svg': 'image/svg+xml',
    '.woff': 'font/woff',
    '.woff2': 'font/woff2',
}

WHITENOISE_AUTOREFRESH = DEBUG
WHITENOISE_USE_FINDERS = DEBUG
WHITENOISE_ALLOW_ALL_ORIGINS = False
=======
>>>>>>> e097b66e17a2ea974af903e357531f5ddcf8880b

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        # ✅ Sans manifest = plus tolérant
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Affichage configuration
print(f"📦 Static/Media Configuration:")
print(f"   Static URL: {STATIC_URL}")
print(f"   Static Root: {STATIC_ROOT}")
print(f"   Static Dirs: {STATICFILES_DIRS}")
print(f"   Media URL: {MEDIA_URL}")
print(f"   Media Root: {MEDIA_ROOT}")
print(f"   Docker Mode: {USE_DOCKER}\n")






# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

<<<<<<< HEAD
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
=======
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==========================================
# PERFORMANCE OPTIMIZATIONS
# ==========================================

# Cache configuration - utilisation de cache en mémoire pour le développement
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,  # 5 minutes par défaut
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

# Optimisation des requêtes
if DEBUG:
    # Activer le logging des requêtes SQL en développement
    LOGGING['loggers']['django.db.backends'] = {
        'handlers': ['console'],
        'level': 'DEBUG' if os.getenv('SQL_DEBUG', 'False').lower() == 'true' else 'INFO',
    }

# Optimisation de l'admin Django
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000  # Augmenter si nécessaire pour l'admin

# ============================================================================
# STRIPE CONFIGURATION
# ============================================================================
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')

if not STRIPE_SECRET_KEY and not DEBUG:
    raise ValueError("STRIPE_SECRET_KEY doit être défini en production")
>>>>>>> e097b66e17a2ea974af903e357531f5ddcf8880b
