"""
Django settings for back project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from pathlib import Path
import pymysql
import os
from dotenv import load_dotenv
from corsheaders.defaults import default_headers
from datetime import timedelta


# ============================================================================
# PYMYSQL CONFIGURATION
# ============================================================================
pymysql.install_as_MySQLdb()

# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/
# Déterminer l'environnement (local, dev, prod)
ENVIRONMENT = os.getenv('ENVIRONMENT', 'local')

# Charger le fichier .env approprié
env_file_map = {
    'local': '.env.local',
    'dev': '.env.dev',
    'prod': '.env.prod',
}

env_file = BASE_DIR / env_file_map.get(ENVIRONMENT, '.env.local')
if env_file.exists():
    load_dotenv(env_file)
    print(f"📋 Loaded: {env_file.name}")
else:
    print(f"⚠️  File not found: {env_file.name}")

# Debug mode
DEBUG_STR = os.getenv('DEBUG', 'True')
DEBUG = DEBUG_STR.lower() not in ['false', '0', 'no', 'off', 'n', 'f']
# Détection environnement
IS_LOCAL = os.getenv('IS_LOCAL', 'False').lower() in ('true', '1', 't')
IS_DOCKER = os.getenv('DOCKER', 'True').lower() in ('true', '1', 't')
USE_DOCKER = os.getenv('USE_DOCKER', 'False').lower() in ('true', '1', 't')



# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i%xj*prc&(=!w_y*xzlv^p8y4#$^jze18l^nr3i$r#4335%+l0'

# SECURITY WARNING: don't run with debug turned on in production!
# Définir DEBUG en fonction de l'environnement
DEBUG =  'True'

print(DEBUG)
ALLOWED_HOSTS = ["*"]


# Application definition
# ===========================
# REST FRAMEWORK
# ===========================
# back/settings.py

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'patients.authentication.PatientJWTAuthentication',  # ✅ Ta classe custom EN PREMIER
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',  # Par défaut ouvert
    ),
    'DEFAULT_RENDERER_CLASSES': (
        
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
}

# Configuration JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,  # ❌ Pas de blacklist
    'BLACKLIST_AFTER_ROTATION': False,  # ❌ Pas de blacklist
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# Logging pour debug
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'patients.authentication': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}

# ===========================
# SIMPLE JWT
# ===========================
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    
    # ✅ DÉSACTIVER la blacklist car elle ne fonctionne qu'avec AUTH_USER_MODEL
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_browser_reload',
    'authentification',
    'Home',
    'produits',
    'clients',
    'paniers',
    'commandes',
    'livraisons',
    'utils',





    'corsheaders',# CORS et configuration pour permettre les appels depuis React
    'drf_yasg',


]
# settings.py

# ============================================================================
# CORS 
# ============================================================================

# Détection environnement
IS_LOCAL = os.getenv('IS_LOCAL', 'False').lower() in ('true', '1', 't')
IS_DOCKER = os.getenv('DOCKER', 'True').lower() in ('true', '1', 't')

# URLs selon l'environnement
if IS_LOCAL:
    FRONTEND_URL = 'http://localhost:3007'
    BACKEND_URL = 'http://localhost:8007'
else:  # DOCKER
    FRONTEND_URL =  'laprovidence.data-worlds.com',
    BACKEND_URL =   'api-laprovidence.data-worlds.com'


# ✅ Override avec variables d'environnement
FRONTEND_URL = os.getenv('FRONTEND_URL', FRONTEND_URL)
BACKEND_URL = os.getenv('BACKEND_URL', BACKEND_URL)

print(f"🌐 URLs Configuration:")
print(f"   Frontend: {FRONTEND_URL}")
print(f"   Backend: {BACKEND_URL}\n")


CORS_ALLOWED_ORIGINS = [
      'http://localhost:3007',  # Pour dev local
      'http://localhost:8007',  # Pour dev local
     'https://api-laprovidence.data-worlds.com',
     'https://laprovidence.data-worlds.com'
    ]

# settings.py


CORS_ALLOW_HEADERS = list(default_headers) + [
    'Authorization',
    'Content-Type',  # Ajouter 'Content-Type' si nécessaire
]
CORS_ALLOW_CREDENTIALS = True

# Si tu travailles en développement local
CSRF_COOKIE_SECURE = False  # Ne pas utiliser HTTPS en local
CSRF_USE_SESSIONS = False

CSRF_TRUSTED_ORIGINS = [
      'http://localhost:3007',  # Pour dev local
        'https://api-laprovidence.data-worlds.com',
     'https://laprovidence.data-worlds.com'

]

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS'
]






AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {'max_similarity': 0.7}
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10}  # Exemple : augmenter à 10
    },
    # ... autres validateurs
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django_browser_reload.middleware.BrowserReloadMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]




ROOT_URLCONF = 'back.urls'
TEMPLATE_DIRS = [os.path.join(BASE_DIR, 'web', 'Base')]
TEMPLATE_DIRS += [os.path.join(BASE_DIR, 'web', 'authentification')]

TEMPLATE_DIRS += [os.path.join(BASE_DIR, 'web', 'Home')]
TEMPLATE_DIRS += [os.path.join(BASE_DIR, 'web', 'Base','Error')]
TEMPLATE_DIRS += [os.path.join(BASE_DIR, 'web', 'produits')]
TEMPLATE_DIRS += [os.path.join(BASE_DIR, 'web', 'commandes')]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': TEMPLATE_DIRS,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

            ],

        },
    },
]

WSGI_APPLICATION = 'back.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DATABASE_NAME', 'LaProvidenceDev'),
        'USER': os.getenv('DATABASE_USER', 'DataWorlds'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD', ' '),
        'HOST': os.getenv('DATABASE_HOST', 'dataworlds.direct.quickconnect.to'),
        'PORT': os.getenv('DATABASE_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'use_unicode': True,
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'connect_timeout': 10,
        },

    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
 
# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'FR-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# ==========================================
# STATIC FILES
# ==========================================

STATIC_URL = '/static/'

# Répertoires contenant les fichiers statiques sources (développement)
# Commenté pour production avec Whitenoise
# STATICFILES_DIRS = [BASE_DIR / 'web' / 'static']

# ✅ CORRECTION : Chemin absolu pour collectstatic (production)
STATIC_ROOT = BASE_DIR / 'static'

# ==========================================
# MEDIA FILES
# ==========================================

MEDIA_URL = '/media/'

# ✅ CORRECTION : Chemin selon l'environnement
if USE_DOCKER:
   MEDIA_ROOT = Path('/app/media')

else:
    MEDIA_ROOT = BASE_DIR / 'media'

# ==========================================
# WHITENOISE STORAGE
# ==========================================


STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        # ✅ Sans manifest = plus tolérant
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Affichage configuration
print(f"📦 Static/Media Configuration:")
print(f"   Static URL: {STATIC_URL}")
print(f"   Static Root: {STATIC_ROOT}")
print(f"   Static Dirs: {STATICFILES_DIRS}")
print(f"   Media URL: {MEDIA_URL}")
print(f"   Media Root: {MEDIA_ROOT}")
print(f"   Docker Mode: {USE_DOCKER}\n")






# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'