# Generated by Django 4.2.7 on 2025-12-08 19:24

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paniers', '0001_initial'),
        ('produits', '0001_initial'),
        ('clients', '0001_initial'),
        ('livraisons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Numéro de commande')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('en_livraison', 'En livraison'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('avancement', models.FloatField(default=0.0, help_text="Pourcentage d'avancement de la commande", verbose_name='Avancement (%)')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total HT')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='clients.client')),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='livraisons.livreur')),
                ('panier', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande', to='paniers.panier')),
                ('point_relais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='livraisons.pointrelais')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(max_length=255)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('client_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('livreur_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('point_relais_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_commande', models.CharField(db_index=True, max_length=255, unique=True)),
                ('date_commande', models.DateTimeField()),
                ('date_archivage', models.DateTimeField(auto_now_add=True)),
                ('statut_final', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('en_livraison', 'En livraison'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], max_length=50)),
                ('action', models.CharField(choices=[('terminer', 'Terminée'), ('annuler', 'Annulée'), ('reouvrir', 'Réouverture')], default='terminer', max_length=50)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('id_panier', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_commandes', to='clients.client')),
                ('commande', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique', to='commandes.commande')),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livraisons.livreur')),
                ('point_relais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livraisons.pointrelais')),
            ],
            options={
                'verbose_name': 'Historique commande',
                'verbose_name_plural': 'Historiques commandes',
                'ordering': ['-date_archivage'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueLignePanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=255, verbose_name='Nom du produit')),
                ('reference_produit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire HT')),
                ('poids', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=8, verbose_name='Poids (kg)')),
                ('statut', models.CharField(choices=[('en_attente', '⏳ En attente'), ('en_preparation', '🔄 En préparation'), ('en_livraison', '🚚 En livraison'), ('en_stock', '✅ En stock'), ('arrivee', '📥 Arrivé'), ('rupture', '❌ Rupture de stock'), ('archive', '📦 Archivé')], default='en_attente', max_length=50, verbose_name='Statut')),
                ('date_archivage', models.DateTimeField(auto_now_add=True, verbose_name="Date d'archivage")),
                ('historique_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.historiquecommande')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Historique ligne panier',
                'verbose_name_plural': 'Historiques lignes panier',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['historique_commande'], name='commandes_h_histori_fb56d1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='historiquecommande',
            index=models.Index(fields=['numero_commande'], name='commandes_h_numero__f17e24_idx'),
        ),
        migrations.AddIndex(
            model_name='historiquecommande',
            index=models.Index(fields=['-date_archivage'], name='commandes_h_date_ar_1f117a_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['numero_commande'], name='commandes_c_numero__ab62be_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['statut'], name='commandes_c_statut_7ba50d_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['-date_commande'], name='commandes_c_date_co_f0b5d9_idx'),
        ),
    ]
